(setq ring-bell-function 'ignore)
(require 'linum)
(global-linum-mode)
(column-number-mode)
(require 'whitespace)
(setq whitespace-style
      '(face trailing tab-mark))
(global-whitespace-mode)
(show-paren-mode 1)
(dolist (hook '(text-mode-hook))
  (add-hook hook (lambda () (flyspell-mode 1))))
(dolist (hook '(change-log-mode-hook log-edit-mode-hook))
  (add-hook hook (lambda () (flyspell-mode -1))))
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(setq indent-line-function 'insert-tab)
